#!/usr/bin/env bash

usage(){
  echo "Usage: [OPTION]... [FILES]..."
}

backup(){
  # TODO:
  #   - Look into getopt vs getopts
  local destination;
  while getopts "d:" option;
  do
    case "${option}" in
      d)
        if [ -d "$OPTARG" ]; then # TODO: Bug: Fails on current directory '.'
          echo "Destination Not Found: '$OPTARG'"
          return 1
        fi
        destination=$OPTARG
        ;;
      ?)
        usage
        return 1;
        ;;
      *)
        echo "OPT: None"
        ;;
    esac
  done
  shift $((OPTIND-1)) # Shift to position of next arg after options

  if [ -z $destination ];then
    destination="."
  fi

  echo "DEST: $destination"
  local files=$*
  for file in $files
  do
    if [ -e $file ]; then
      cp $file $destination
    else
      echo "File Not Found: $file"
      return 1;
    fi
  done
}

backup $@
